---
- hosts: cli
  become: true
  tasks:
    - name: Instalar Firefox e X11 forwarding
      apt:
        name:
          - firefox-esr
          - xauth
        state: present
        update_cache: yes

    - name: Ativar X11 Forwarding no SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^X11Forwarding'
        line: 'X11Forwarding yes'

    - name: Reiniciar SSH
      service:
        name: ssh
        state: restarted

    - name: Instalar autofs
      apt:
        name: autofs
        state: present

    - name: Configurar autofs
      copy:
        dest: /etc/auto.master
        content: |
          /var/nfs /etc/auto.nfs --ghost

    - name: Criar mapa /etc/auto.nfs
      copy:
        dest: /etc/auto.nfs
        content: |
          dados -rw,soft,intr,rsize=8192,wsize=8192 arq.maricleia.devops:/dados/nfs

    - name: Reiniciar autofs
      service:
        name: autofs
        state: restarted