---
- hosts: db
  become: true
  tasks:
    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Instalar autofs
      apt:
        name: autofs
        state: present

    - name: Configurar montagem NFS automática
      copy:
        dest: /etc/auto.master
        content: |
          /var/nfs /etc/auto.nfs --ghost

    - name: Criar mapa /etc/auto.nfs
      copy:
        dest: /etc/auto.nfs
        content: |
          dados -rw,soft,intr,rsize=8192,wsize=8192 arq.maricleia.devops:/dados/nfs

    - name: Reiniciar autofs
      service:
        name: autofs
        state: restarted